import {Injectable} from '@angular/core';
import {HttpClient} from '@angular/common/http';

@Injectable({
  providedIn: 'root'
})
export class AlgemeneVoorwaardenService  {
  private text =
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vulputate a ante eget aliquam. Quisque posuere magna sit amet nisl porttitor aliquet. Phasellus non congue eros. Praesent tincidunt, lorem in convallis condimentum, massa lacus maximus sapien, nec laoreet tellus massa in libero. Fusce volutpat scelerisque ante, nec vestibulum diam rutrum quis. Praesent quis arcu dui. Ut tincidunt ipsum turpis, semper tristique velit ultrices vitae. Curabitur et nunc quam. Cras fringilla orci eu felis semper vulputate. Quisque id turpis rhoncus, mollis risus quis, sagittis augue. Cras vel urna id nisl vehicula tincidunt sed quis sem. Donec eget lacus diam. Integer et volutpat orci. Mauris vitae tortor ut felis vestibulum cursus ut non magna.\n' +
    '\n' +
    'Curabitur volutpat est id maximus malesuada. Sed convallis suscipit diam. Sed imperdiet velit vel est facilisis, ut euismod urna tincidunt. Morbi sit amet est sed sem interdum interdum quis eget libero. Vestibulum eu varius libero, id aliquet arcu. Nunc posuere accumsan justo nec luctus. Integer nibh lectus, auctor quis risus et, sollicitudin consectetur nunc. Sed laoreet feugiat sem, eu luctus lacus porta ut. Suspendisse facilisis neque id odio elementum, in sodales ipsum gravida. Sed egestas efficitur tortor ac ornare. Curabitur consequat ex in libero blandit viverra. Phasellus vel sollicitudin nulla, eu sollicitudin velit. Nulla fringilla augue non diam luctus, a rutrum turpis venenatis. Fusce at vulputate quam. Integer ac eleifend metus. Suspendisse aliquam, diam eu rutrum pellentesque, tellus mi auctor tellus, quis elementum urna metus eleifend lacus.\n' +
    '\n' +
    'Etiam sed sapien in lorem posuere venenatis. Curabitur lobortis tortor nec dolor sollicitudin posuere. Nullam imperdiet arcu sit amet facilisis dignissim. Nullam ullamcorper consectetur justo id lobortis. Duis cursus, quam eleifend malesuada euismod, turpis nunc bibendum elit, id tincidunt ante quam eget nulla. Proin augue libero, accumsan vitae quam a, varius pharetra massa. Vestibulum varius augue eget pellentesque vestibulum. Mauris et aliquet massa. Integer rutrum posuere risus eget tempus. Pellentesque sagittis neque arcu, eu vulputate lorem semper nec. Sed vulputate eros eu libero tristique, ut fermentum velit convallis. Pellentesque blandit sem sed purus vehicula faucibus. Aliquam erat volutpat. Aliquam mi dui, ullamcorper sit amet fermentum sit amet, efficitur placerat arcu.\n' +
    '\n' +
    'Praesent porta diam non sapien aliquet, et pellentesque magna vestibulum. Vestibulum blandit est non turpis tincidunt rutrum. Ut suscipit imperdiet laoreet. In hac habitasse platea dictumst. Mauris posuere tempus nisi, in euismod lorem laoreet tincidunt. Mauris tincidunt, tortor ac iaculis auctor, elit justo rhoncus velit, a consectetur magna lorem quis orci. In bibendum ligula sed arcu aliquet, ut volutpat dui scelerisque. Cras quis sollicitudin lectus. Nam lacinia dapibus varius. Aenean placerat sit amet mi non iaculis. Aliquam imperdiet orci nec ullamcorper elementum. Nullam a erat nec turpis cursus maximus eu sit amet metus. Sed mollis rutrum nunc. Mauris nisi velit, elementum sit amet turpis at, semper porta est. Integer varius turpis massa, sit amet condimentum tortor vestibulum eget. Quisque ipsum orci, consectetur et urna nec, malesuada ullamcorper leo.\n' +
    '\n' +
    'Nam ornare sodales aliquet. Etiam rhoncus dolor vitae leo sagittis, at malesuada sem scelerisque. Quisque mollis consectetur orci a tincidunt. Quisque eu euismod leo. Sed luctus vehicula egestas. Fusce ullamcorper orci sit amet tortor lobortis interdum. Fusce faucibus mattis augue. Nullam bibendum ac eros nec aliquet. Donec porta aliquam urna, in bibendum ipsum bibendum ultricies. Sed ut lacus a massa vulputate porttitor sit amet nec lacus. Phasellus vehicula congue porta. Ut eget quam consequat, molestie nisi quis, congue dolor. In odio nulla, pretium eget dolor id, consequat venenatis est.\n' +
    '\n' +
    'Sed semper pulvinar eleifend. Vivamus a nunc at sapien blandit lobortis. Pellentesque bibendum turpis at enim accumsan, et efficitur urna gravida. Donec massa dolor, gravida semper nibh in, venenatis imperdiet ligula. Sed mauris nulla, porta vel enim eu, placerat posuere felis. Pellentesque euismod egestas leo et efficitur. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam sed ante sollicitudin quam sodales lacinia. Quisque consequat tortor sit amet erat tempor euismod. Pellentesque vitae nunc purus. Suspendisse iaculis sem sed magna scelerisque porta. Morbi non venenatis lacus, ut blandit lacus.\n' +
    '\n' +
    'Nam non augue nec enim maximus aliquet et id augue. Aliquam pellentesque justo orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eu volutpat felis. Mauris ultricies pharetra elementum. Nullam at risus eu odio ultrices commodo id a nunc. Cras posuere orci dapibus congue volutpat. Sed cursus, turpis at facilisis condimentum, eros mauris convallis felis, eget lacinia nisi lectus eu sem. Integer sit amet ex turpis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed vitae purus purus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus feugiat pellentesque nisl vel tempor. Pellentesque vel nibh tincidunt arcu porttitor blandit. Etiam purus lacus, fringilla eu mauris sit amet, sagittis volutpat ligula.\n' +
    '\n' +
    'Nunc fringilla risus non condimentum vehicula. Nulla malesuada aliquet mauris vel venenatis. Sed lorem purus, vehicula eget posuere quis, laoreet vitae justo. Donec eu elit posuere, porttitor justo sed, rutrum tellus. Curabitur scelerisque tristique nisl, id faucibus purus elementum quis. Praesent eu feugiat lorem, id pharetra mi. Cras nisi arcu, volutpat ac mauris at, mollis tincidunt elit. Etiam mauris diam, ultrices eget dapibus et, mattis at ante. Duis feugiat augue id nibh pretium sodales. Pellentesque auctor, lectus id posuere molestie, urna neque bibendum ante, non interdum dolor lorem at leo. Aliquam vel malesuada justo.\n' +
    '\n' +
    'Suspendisse euismod est non sagittis tincidunt. Aliquam erat volutpat. Maecenas condimentum est et aliquet placerat. Pellentesque sagittis erat id ante viverra consectetur a et nulla. Vivamus elementum venenatis nulla, in tempus metus. Donec blandit neque eget luctus aliquet. Pellentesque cursus, metus facilisis varius elementum, libero neque iaculis lectus, nec euismod leo est id odio. Suspendisse id interdum felis. Integer ac ultrices libero. Praesent euismod ex et nibh faucibus aliquet. Nam lacinia purus aliquam luctus laoreet. Nullam molestie tempus porta. Nullam vel interdum nisi.\n' +
    '\n' +
    'Morbi malesuada id magna id ultrices. Fusce mi elit, convallis ornare porttitor et, elementum non lacus. Duis convallis odio non venenatis interdum. Etiam feugiat efficitur lorem ut elementum. Nunc sagittis, erat ac vestibulum dapibus, nibh ligula laoreet velit, vitae facilisis justo nulla ac magna. Suspendisse quis consectetur enim, in tincidunt eros. Duis placerat mauris ut purus eleifend, in porta ipsum sollicitudin. Aliquam convallis dictum turpis. Praesent tortor tellus, laoreet quis purus vitae, mollis malesuada risus. Ut quam diam, bibendum at felis non, condimentum tempus risus. Vestibulum dignissim efficitur elit eu pulvinar. Sed imperdiet massa vitae lacus accumsan, sit amet auctor lacus faucibus. Quisque ac lorem euismod, posuere metus ut, consectetur leo. Cras eu leo nunc.\n';

  constructor(private httpClient: HttpClient) { }

  getAlgemeneVoorwaarden() {
    return this.text;
  }
}
